#!/bin/bash
# Обновление системы
echo -e "\033[1;36m"
echo -e "███████╗░█████╗░████████╗████████╗██╗░░░██╗░█████╗░"
echo -e "██╔════╝██╔══██╗╚══██╔══╝╚══██╔══╝██║░░░██║██╔══██╗"
echo -e "█████╗░░██║░░██║░░░██║░░░░░░██║░░░██║░░░██║███████║"
echo -e "██╔══╝░░██║░░██║░░░██║░░░░░░██║░░░██║░░░██║██╔══██║"
echo -e "██║░░░░░╚█████╔╝░░░██║░░░░░░██║░░░╚██████╔╝██║░░██║"
echo -e "╚═╝░░░░░░╚════╝░░░░╚═╝░░░░░░╚═╝░░░░╚═════╝░╚═╝░░╚═╝"
echo -e "\033[1;34m"

echo
echo -e "\033[0m"
echo "Обновление списка пакетов и установка обновлений..."
sudo apt update -y && sudo apt upgrade -y

# Установка необходимых пакетов
echo "Установка необходимых пакетов..."
PACKAGES=(
  curl
  git
  jq
  lz4
  build-essential
  unzip
  make
  gcc
  ncdu
  cmake
  clang
  pkg-config
  libssl-dev
  python3-pip
  protobuf-compiler
  docker.io
  dos2unix
  screen
  mc
)

for PACKAGE in "${PACKAGES[@]}"; do
  if [ "$PACKAGE" == "docker.io" ]; then
    echo "Установка Docker..."
    curl -fsSL https://get.docker.com | bash -s docker
    if [ $? -eq 0 ]; then
      sudo systemctl start docker
      sudo systemctl enable docker.service
      echo "Docker успешно установлен и запущен."
    else
      echo "Ошибка при установке Docker. Пропускаем..."
    fi
  else
    echo "Установка $PACKAGE..."
    sudo apt install -y "$PACKAGE"
    if [ $? -eq 0 ]; then
      echo "$PACKAGE успешно установлен."
    else
      echo "Ошибка при установке $PACKAGE. Пропускаем..."
    fi
  fi
done

# Печать завершения процесса
echo "Начальная настройка сервера завершена."
